name: file-renamer
base: core18
version: '1.0.1'
summary: A desktop GUI app for renaming files.
description: |
	Rename files using a GUI desktop app for Linux, Windows & macOS.
grade: stable
confinement: strict
apps:
	file-renamer:
		command: bin/file-renamer
parts:
	file-renamer:
		source: https://github.com/mcarlos101/file-renamer
		plugin: python
